var hierarchy =
[
    [ "UMPS::ProxyServices::PacketCache::CappedCollection< T >", "class_u_m_p_s_1_1_proxy_services_1_1_packet_cache_1_1_capped_collection.html", null ],
    [ "UMPS::ProxyServices::PacketCache::CircularBuffer< T >", "class_u_m_p_s_1_1_proxy_services_1_1_packet_cache_1_1_circular_buffer.html", null ],
    [ "UMPS::Messaging::Context", "class_u_m_p_s_1_1_messaging_1_1_context.html", null ],
    [ "UMPS::ProxyServices::Incrementer::Counter", "class_u_m_p_s_1_1_proxy_services_1_1_incrementer_1_1_counter.html", null ],
    [ "UMPS::MessageFormats::DataPacket< T >", "class_u_m_p_s_1_1_message_formats_1_1_data_packet.html", null ],
    [ "UMPS::Services::ConnectionInformation::SocketDetails::Dealer", "class_u_m_p_s_1_1_services_1_1_connection_information_1_1_socket_details_1_1_dealer.html", null ],
    [ "UMPS::Services::ConnectionInformation::Details", "class_u_m_p_s_1_1_services_1_1_connection_information_1_1_details.html", null ],
    [ "UMPS::Authentication::IAuthenticator", "class_u_m_p_s_1_1_authentication_1_1_i_authenticator.html", [
      [ "UMPS::Authentication::Grasslands", "class_u_m_p_s_1_1_authentication_1_1_grasslands.html", null ],
      [ "UMPS::Authentication::SQLite3Authenticator", "class_u_m_p_s_1_1_authentication_1_1_s_q_lite3_authenticator.html", null ]
    ] ],
    [ "UMPS::Broadcasts::IBroadcast", "class_u_m_p_s_1_1_broadcasts_1_1_i_broadcast.html", null ],
    [ "UMPS::Logging::ILog", "class_u_m_p_s_1_1_logging_1_1_i_log.html", [
      [ "UMPS::Logging::DailyFile", "class_u_m_p_s_1_1_logging_1_1_daily_file.html", null ],
      [ "UMPS::Logging::LogIt", "class_u_m_p_s_1_1_logging_1_1_log_it.html", null ],
      [ "UMPS::Logging::StandardOut", "class_u_m_p_s_1_1_logging_1_1_standard_out.html", null ]
    ] ],
    [ "UMPS::MessageFormats::IMessage", "class_u_m_p_s_1_1_message_formats_1_1_i_message.html", [
      [ "UMPS::Authentication::User", "class_u_m_p_s_1_1_authentication_1_1_user.html", null ],
      [ "UMPS::MessageFormats::Failure", "class_u_m_p_s_1_1_message_formats_1_1_failure.html", null ],
      [ "UMPS::MessageFormats::Pick", "class_u_m_p_s_1_1_message_formats_1_1_pick.html", null ],
      [ "UMPS::MessageFormats::Text", "class_u_m_p_s_1_1_message_formats_1_1_text.html", null ],
      [ "UMPS::ProxyBroadcasts::Heartbeat::Status", "class_u_m_p_s_1_1_proxy_broadcasts_1_1_heartbeat_1_1_status.html", null ],
      [ "UMPS::ProxyServices::Command::AvailableModulesRequest", "class_u_m_p_s_1_1_proxy_services_1_1_command_1_1_available_modules_request.html", null ],
      [ "UMPS::ProxyServices::Command::AvailableModulesResponse", "class_u_m_p_s_1_1_proxy_services_1_1_command_1_1_available_modules_response.html", null ],
      [ "UMPS::ProxyServices::Command::RegistrationRequest", "class_u_m_p_s_1_1_proxy_services_1_1_command_1_1_registration_request.html", null ],
      [ "UMPS::ProxyServices::Command::RegistrationResponse", "class_u_m_p_s_1_1_proxy_services_1_1_command_1_1_registration_response.html", null ],
      [ "UMPS::ProxyServices::Incrementer::IncrementRequest", "class_u_m_p_s_1_1_proxy_services_1_1_incrementer_1_1_increment_request.html", null ],
      [ "UMPS::ProxyServices::Incrementer::IncrementResponse", "class_u_m_p_s_1_1_proxy_services_1_1_incrementer_1_1_increment_response.html", null ],
      [ "UMPS::ProxyServices::Incrementer::ItemsRequest", "class_u_m_p_s_1_1_proxy_services_1_1_incrementer_1_1_items_request.html", null ],
      [ "UMPS::ProxyServices::Incrementer::ItemsResponse", "class_u_m_p_s_1_1_proxy_services_1_1_incrementer_1_1_items_response.html", null ],
      [ "UMPS::ProxyServices::PacketCache::BulkDataRequest", "class_u_m_p_s_1_1_proxy_services_1_1_packet_cache_1_1_bulk_data_request.html", null ],
      [ "UMPS::ProxyServices::PacketCache::BulkDataResponse< T >", "class_u_m_p_s_1_1_proxy_services_1_1_packet_cache_1_1_bulk_data_response.html", null ],
      [ "UMPS::ProxyServices::PacketCache::DataRequest", "class_u_m_p_s_1_1_proxy_services_1_1_packet_cache_1_1_data_request.html", null ],
      [ "UMPS::ProxyServices::PacketCache::DataResponse< T >", "class_u_m_p_s_1_1_proxy_services_1_1_packet_cache_1_1_data_response.html", null ],
      [ "UMPS::ProxyServices::PacketCache::SensorRequest", "class_u_m_p_s_1_1_proxy_services_1_1_packet_cache_1_1_sensor_request.html", null ],
      [ "UMPS::ProxyServices::PacketCache::SensorResponse", "class_u_m_p_s_1_1_proxy_services_1_1_packet_cache_1_1_sensor_response.html", null ],
      [ "UMPS::Services::Command::AvailableCommandsRequest", "class_u_m_p_s_1_1_services_1_1_command_1_1_available_commands_request.html", null ],
      [ "UMPS::Services::Command::AvailableCommandsResponse", "class_u_m_p_s_1_1_services_1_1_command_1_1_available_commands_response.html", null ],
      [ "UMPS::Services::Command::CommandRequest", "class_u_m_p_s_1_1_services_1_1_command_1_1_command_request.html", null ],
      [ "UMPS::Services::Command::CommandResponse", "class_u_m_p_s_1_1_services_1_1_command_1_1_command_response.html", null ],
      [ "UMPS::Services::Command::TerminateRequest", "class_u_m_p_s_1_1_services_1_1_command_1_1_terminate_request.html", null ],
      [ "UMPS::Services::Command::TerminateResponse", "class_u_m_p_s_1_1_services_1_1_command_1_1_terminate_response.html", null ],
      [ "UMPS::Services::ConnectionInformation::AvailableConnectionsRequest", "class_u_m_p_s_1_1_services_1_1_connection_information_1_1_available_connections_request.html", null ],
      [ "UMPS::Services::ConnectionInformation::AvailableConnectionsResponse", "class_u_m_p_s_1_1_services_1_1_connection_information_1_1_available_connections_response.html", null ],
      [ "UMPS::Services::ModuleRegistry::RegisteredModulesRequest", "class_u_m_p_s_1_1_services_1_1_module_registry_1_1_registered_modules_request.html", null ],
      [ "UMPS::Services::ModuleRegistry::RegisteredModulesResponse", "class_u_m_p_s_1_1_services_1_1_module_registry_1_1_registered_modules_response.html", null ],
      [ "UMPS::Services::ModuleRegistry::RegistrationRequest", "class_u_m_p_s_1_1_services_1_1_module_registry_1_1_registration_request.html", null ],
      [ "UMPS::Services::ModuleRegistry::RegistrationResponse", "class_u_m_p_s_1_1_services_1_1_module_registry_1_1_registration_response.html", null ]
    ] ],
    [ "UMPS::Modules::IModule", "class_u_m_p_s_1_1_modules_1_1_i_module.html", null ],
    [ "UMPS::ProxyServices::PacketCache::InterpolatedSignal< T >", "struct_u_m_p_s_1_1_proxy_services_1_1_packet_cache_1_1_interpolated_signal.html", null ],
    [ "UMPS::Modules::IProcess", "class_u_m_p_s_1_1_modules_1_1_i_process.html", [
      [ "UMPS::ProxyBroadcasts::Heartbeat::PublisherProcess", "class_u_m_p_s_1_1_proxy_broadcasts_1_1_heartbeat_1_1_publisher_process.html", null ],
      [ "UMPS::ProxyServices::Command::ReplierProcess", "class_u_m_p_s_1_1_proxy_services_1_1_command_1_1_replier_process.html", null ]
    ] ],
    [ "IProxy", null, [
      [ "UMPS::ProxyBroadcasts::Heartbeat::Proxy", "class_u_m_p_s_1_1_proxy_broadcasts_1_1_heartbeat_1_1_proxy.html", null ]
    ] ],
    [ "UMPS::Services::IService", "class_u_m_p_s_1_1_services_1_1_i_service.html", [
      [ "UMPS::Services::Command::Service", "class_u_m_p_s_1_1_services_1_1_command_1_1_service.html", null ],
      [ "UMPS::Services::ConnectionInformation::Service", "class_u_m_p_s_1_1_services_1_1_connection_information_1_1_service.html", null ],
      [ "UMPS::Services::ModuleRegistry::Service", "class_u_m_p_s_1_1_services_1_1_module_registry_1_1_service.html", null ]
    ] ],
    [ "UMPS::Authentication::Certificate::Keys", "class_u_m_p_s_1_1_authentication_1_1_certificate_1_1_keys.html", null ],
    [ "Level", "class_level.html", null ],
    [ "UMPS::MessageFormats::Messages", "class_u_m_p_s_1_1_message_formats_1_1_messages.html", null ],
    [ "UMPS::ProxyServices::Command::ModuleDetails", "class_u_m_p_s_1_1_proxy_services_1_1_command_1_1_module_details.html", null ],
    [ "UMPS::Services::Command::ModuleDetails", "class_u_m_p_s_1_1_services_1_1_command_1_1_module_details.html", null ],
    [ "UMPS::Services::Command::ModuleTable", "class_u_m_p_s_1_1_services_1_1_command_1_1_module_table.html", null ],
    [ "UMPS::ProxyServices::Incrementer::Options", "class_u_m_p_s_1_1_proxy_services_1_1_incrementer_1_1_options.html", null ],
    [ "UMPS::Modules::ProcessManager", "class_u_m_p_s_1_1_modules_1_1_process_manager.html", null ],
    [ "Proxy", "class_proxy.html", null ],
    [ "UMPS::Messaging::RouterDealer::Proxy", "class_u_m_p_s_1_1_messaging_1_1_router_dealer_1_1_proxy.html", null ],
    [ "UMPS::Messaging::XPublisherXSubscriber::Proxy", "class_u_m_p_s_1_1_messaging_1_1_x_publisher_x_subscriber_1_1_proxy.html", null ],
    [ "UMPS::ProxyBroadcasts::Proxy", "class_u_m_p_s_1_1_proxy_broadcasts_1_1_proxy.html", null ],
    [ "UMPS::ProxyServices::Command::Proxy", "class_u_m_p_s_1_1_proxy_services_1_1_command_1_1_proxy.html", null ],
    [ "UMPS::ProxyServices::Proxy", "class_u_m_p_s_1_1_proxy_services_1_1_proxy.html", null ],
    [ "UMPS::Services::ConnectionInformation::SocketDetails::Proxy", "class_u_m_p_s_1_1_services_1_1_connection_information_1_1_socket_details_1_1_proxy.html", null ],
    [ "UMPS::Messaging::RouterDealer::ProxyOptions", "class_u_m_p_s_1_1_messaging_1_1_router_dealer_1_1_proxy_options.html", null ],
    [ "UMPS::Messaging::XPublisherXSubscriber::ProxyOptions", "class_u_m_p_s_1_1_messaging_1_1_x_publisher_x_subscriber_1_1_proxy_options.html", null ],
    [ "UMPS::ProxyBroadcasts::Heartbeat::ProxyOptions", "class_u_m_p_s_1_1_proxy_broadcasts_1_1_heartbeat_1_1_proxy_options.html", null ],
    [ "UMPS::ProxyBroadcasts::ProxyOptions", "class_u_m_p_s_1_1_proxy_broadcasts_1_1_proxy_options.html", null ],
    [ "UMPS::ProxyServices::Command::ProxyOptions", "class_u_m_p_s_1_1_proxy_services_1_1_command_1_1_proxy_options.html", null ],
    [ "UMPS::ProxyServices::ProxyOptions", "class_u_m_p_s_1_1_proxy_services_1_1_proxy_options.html", null ],
    [ "UMPS::Messaging::PublisherSubscriber::Publisher", "class_u_m_p_s_1_1_messaging_1_1_publisher_subscriber_1_1_publisher.html", null ],
    [ "UMPS::Messaging::XPublisherXSubscriber::Publisher", "class_u_m_p_s_1_1_messaging_1_1_x_publisher_x_subscriber_1_1_publisher.html", null ],
    [ "UMPS::ProxyBroadcasts::Heartbeat::Publisher", "class_u_m_p_s_1_1_proxy_broadcasts_1_1_heartbeat_1_1_publisher.html", null ],
    [ "UMPS::ProxyBroadcasts::Pick::Publisher", "class_u_m_p_s_1_1_proxy_broadcasts_1_1_pick_1_1_publisher.html", null ],
    [ "UMPS::Services::ConnectionInformation::SocketDetails::Publisher", "class_u_m_p_s_1_1_services_1_1_connection_information_1_1_socket_details_1_1_publisher.html", null ],
    [ "UMPS::Messaging::PublisherSubscriber::PublisherOptions", "class_u_m_p_s_1_1_messaging_1_1_publisher_subscriber_1_1_publisher_options.html", null ],
    [ "UMPS::Messaging::XPublisherXSubscriber::PublisherOptions", "class_u_m_p_s_1_1_messaging_1_1_x_publisher_x_subscriber_1_1_publisher_options.html", null ],
    [ "UMPS::ProxyBroadcasts::Heartbeat::PublisherOptions", "class_u_m_p_s_1_1_proxy_broadcasts_1_1_heartbeat_1_1_publisher_options.html", null ],
    [ "UMPS::ProxyBroadcasts::Pick::PublisherOptions", "class_u_m_p_s_1_1_proxy_broadcasts_1_1_pick_1_1_publisher_options.html", null ],
    [ "UMPS::ProxyBroadcasts::Heartbeat::PublisherProcessOptions", "class_u_m_p_s_1_1_proxy_broadcasts_1_1_heartbeat_1_1_publisher_process_options.html", null ],
    [ "RegistrationReturnCode", "class_registration_return_code.html", null ],
    [ "UMPS::ProxyServices::Command::Replier", "class_u_m_p_s_1_1_proxy_services_1_1_command_1_1_replier.html", null ],
    [ "UMPS::ProxyServices::Incrementer::Replier", "class_u_m_p_s_1_1_proxy_services_1_1_incrementer_1_1_replier.html", null ],
    [ "UMPS::ProxyServices::PacketCache::Replier< T >", "class_u_m_p_s_1_1_proxy_services_1_1_packet_cache_1_1_replier.html", null ],
    [ "UMPS::ProxyServices::Command::ReplierOptions", "class_u_m_p_s_1_1_proxy_services_1_1_command_1_1_replier_options.html", null ],
    [ "UMPS::ProxyServices::Incrementer::ReplierOptions", "class_u_m_p_s_1_1_proxy_services_1_1_incrementer_1_1_replier_options.html", null ],
    [ "UMPS::ProxyServices::PacketCache::ReplierOptions", "class_u_m_p_s_1_1_proxy_services_1_1_packet_cache_1_1_replier_options.html", null ],
    [ "UMPS::Messaging::RouterDealer::Reply", "class_u_m_p_s_1_1_messaging_1_1_router_dealer_1_1_reply.html", null ],
    [ "UMPS::Services::ConnectionInformation::SocketDetails::Reply", "class_u_m_p_s_1_1_services_1_1_connection_information_1_1_socket_details_1_1_reply.html", null ],
    [ "UMPS::Messaging::RouterDealer::ReplyOptions", "class_u_m_p_s_1_1_messaging_1_1_router_dealer_1_1_reply_options.html", null ],
    [ "UMPS::Messaging::RequestRouter::Request", "class_u_m_p_s_1_1_messaging_1_1_request_router_1_1_request.html", null ],
    [ "UMPS::Messaging::RouterDealer::Request", "class_u_m_p_s_1_1_messaging_1_1_router_dealer_1_1_request.html", null ],
    [ "UMPS::Services::ConnectionInformation::SocketDetails::Request", "class_u_m_p_s_1_1_services_1_1_connection_information_1_1_socket_details_1_1_request.html", null ],
    [ "UMPS::Messaging::RequestRouter::RequestOptions", "class_u_m_p_s_1_1_messaging_1_1_request_router_1_1_request_options.html", null ],
    [ "UMPS::Messaging::RouterDealer::RequestOptions", "class_u_m_p_s_1_1_messaging_1_1_router_dealer_1_1_request_options.html", null ],
    [ "UMPS::ProxyServices::Command::Requestor", "class_u_m_p_s_1_1_proxy_services_1_1_command_1_1_requestor.html", null ],
    [ "UMPS::ProxyServices::Incrementer::Requestor", "class_u_m_p_s_1_1_proxy_services_1_1_incrementer_1_1_requestor.html", null ],
    [ "UMPS::ProxyServices::PacketCache::Requestor", "class_u_m_p_s_1_1_proxy_services_1_1_packet_cache_1_1_requestor.html", null ],
    [ "UMPS::Services::Command::Requestor", "class_u_m_p_s_1_1_services_1_1_command_1_1_requestor.html", null ],
    [ "UMPS::Services::ConnectionInformation::Requestor", "class_u_m_p_s_1_1_services_1_1_connection_information_1_1_requestor.html", null ],
    [ "UMPS::ProxyServices::Command::RequestorOptions", "class_u_m_p_s_1_1_proxy_services_1_1_command_1_1_requestor_options.html", null ],
    [ "UMPS::ProxyServices::Incrementer::RequestorOptions", "class_u_m_p_s_1_1_proxy_services_1_1_incrementer_1_1_requestor_options.html", null ],
    [ "UMPS::ProxyServices::PacketCache::RequestorOptions", "class_u_m_p_s_1_1_proxy_services_1_1_packet_cache_1_1_requestor_options.html", null ],
    [ "UMPS::Services::Command::RequestorOptions", "class_u_m_p_s_1_1_services_1_1_command_1_1_requestor_options.html", null ],
    [ "UMPS::Services::ConnectionInformation::RequestorOptions", "class_u_m_p_s_1_1_services_1_1_connection_information_1_1_requestor_options.html", null ],
    [ "UMPS::Messaging::RequestRouter::Router", "class_u_m_p_s_1_1_messaging_1_1_request_router_1_1_router.html", null ],
    [ "UMPS::Services::ConnectionInformation::SocketDetails::Router", "class_u_m_p_s_1_1_services_1_1_connection_information_1_1_socket_details_1_1_router.html", null ],
    [ "UMPS::Messaging::RequestRouter::RouterOptions", "class_u_m_p_s_1_1_messaging_1_1_request_router_1_1_router_options.html", null ],
    [ "SecurityLevel", "class_security_level.html", null ],
    [ "UMPS::Authentication::Service", "class_u_m_p_s_1_1_authentication_1_1_service.html", null ],
    [ "UMPS::ProxyServices::Incrementer::Service", "class_u_m_p_s_1_1_proxy_services_1_1_incrementer_1_1_service.html", null ],
    [ "UMPS::ProxyServices::PacketCache::Service< T >", "class_u_m_p_s_1_1_proxy_services_1_1_packet_cache_1_1_service.html", null ],
    [ "UMPS::Services::Command::ServiceOptions", "class_u_m_p_s_1_1_services_1_1_command_1_1_service_options.html", null ],
    [ "UMPS::Services::ConnectionInformation::ServiceOptions", "class_u_m_p_s_1_1_services_1_1_connection_information_1_1_service_options.html", null ],
    [ "UMPS::Services::ModuleRegistry::ServiceOptions", "class_u_m_p_s_1_1_services_1_1_module_registry_1_1_service_options.html", null ],
    [ "UMPS::Messaging::SocketOptions", "class_u_m_p_s_1_1_messaging_1_1_socket_options.html", null ],
    [ "UMPS::Messaging::PublisherSubscriber::Subscriber", "class_u_m_p_s_1_1_messaging_1_1_publisher_subscriber_1_1_subscriber.html", null ],
    [ "UMPS::ProxyBroadcasts::Heartbeat::Subscriber", "class_u_m_p_s_1_1_proxy_broadcasts_1_1_heartbeat_1_1_subscriber.html", null ],
    [ "UMPS::ProxyBroadcasts::Pick::Subscriber", "class_u_m_p_s_1_1_proxy_broadcasts_1_1_pick_1_1_subscriber.html", null ],
    [ "UMPS::Services::ConnectionInformation::SocketDetails::Subscriber", "class_u_m_p_s_1_1_services_1_1_connection_information_1_1_socket_details_1_1_subscriber.html", null ],
    [ "UMPS::Messaging::PublisherSubscriber::SubscriberOptions", "class_u_m_p_s_1_1_messaging_1_1_publisher_subscriber_1_1_subscriber_options.html", null ],
    [ "UMPS::ProxyBroadcasts::DataPacket::SubscriberOptions< T >", "class_u_m_p_s_1_1_proxy_broadcasts_1_1_data_packet_1_1_subscriber_options.html", null ],
    [ "UMPS::ProxyBroadcasts::Heartbeat::SubscriberOptions", "class_u_m_p_s_1_1_proxy_broadcasts_1_1_heartbeat_1_1_subscriber_options.html", null ],
    [ "UMPS::ProxyBroadcasts::Pick::SubscriberOptions", "class_u_m_p_s_1_1_proxy_broadcasts_1_1_pick_1_1_subscriber_options.html", null ],
    [ "umps", "classumps.html", null ],
    [ "UMPS::Authentication::Certificate::UserNameAndPassword", "class_u_m_p_s_1_1_authentication_1_1_certificate_1_1_user_name_and_password.html", null ],
    [ "UserPrivileges", "class_user_privileges.html", null ],
    [ "UMPS::ProxyServices::PacketCache::WigginsInterpolator", "class_u_m_p_s_1_1_proxy_services_1_1_packet_cache_1_1_wiggins_interpolator.html", null ],
    [ "UMPS::Services::ConnectionInformation::SocketDetails::XPublisher", "class_u_m_p_s_1_1_services_1_1_connection_information_1_1_socket_details_1_1_x_publisher.html", null ],
    [ "UMPS::Services::ConnectionInformation::SocketDetails::XSubscriber", "class_u_m_p_s_1_1_services_1_1_connection_information_1_1_socket_details_1_1_x_subscriber.html", null ],
    [ "UMPS::Authentication::ZAPOptions", "class_u_m_p_s_1_1_authentication_1_1_z_a_p_options.html", null ]
];