version: 2
jobs:
  build:
    docker:
      - image: bakerb845/umps_ubuntu22
    steps:
      - checkout
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Configuration
          command: |
            if [ -d build ]; then
               echo "Removing build directory"
               rm -rf build
            fi
            mkdir -p build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_FLAGS="-Wall" \
            -DWRAP_PYTHON=ON
      - run:
           name: Build the code
           command: |
            cd build
            make -j 2
      - run:
           name: Test the code
           command: |
            cd build
            ctest --verbose
      - run:
           name: Install Code
           command: |
            cd build
            make install
